---
name: yamllint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Run yamllint
        run: |
          yamllint --no-warnings ./
